name: Build C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up C++ environment
        run: sudo apt-get install -y build-essential cmake
      
      - name: Check C++ version
        run: cmake --version
      
      - name: Clone repository
        run: git clone https://github.com/DrBit-64/readline_my_test.git
      
      - name: Build project
        working-directory: readline_my_test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .